---

- name: install system packages
  package: name={{ item }} state=latest
  with_items:
    - tmux
    - make
    - htop
    - ranger
  become: yes

- name: install pip packages
  pip:
    name: "{{ item }}"
    executable: pip3
    extra_args: --user
  with_items:
    - ptpython
