---

- name: install system packages
  package: name={{ item }} state=latest
  with_items:
    - tmux # terminal multiplexer
    - htop # process diagnostics
    - ranger # file exploler
    - make # build / script automation
    - net-tools
    - network-manager

    - ncftp # improved FTP client
  become: yes

- name: install aptitude on Debian-based systems
  package: name=aptitude state=latest
  become: yes
  when: ansible_os_family == 'Debian'
