---
- name: add my mappings to Polish keyboard xkb config
  become: yes
  blockinfile:
    path: /usr/share/X11/xkb/symbols/pl
    block: "{{ lookup('template', 'templates/keyboard/xkb_includes.j2') }}" 
    insertafter: 'xkb_symbols \"basic\" \{'
    marker: "// {mark} ANSIBLE MANAGED BLOCK"
    regexp: both_capslock_cancel
  notify:
    - reload keyboard layout
