---
- name: add my mappings to Polish keyboard xkb config
  become: yes
  blockinfile:
    path: /usr/share/X11/xkb/symbols/pl
    block: "{{ lookup('template', 'templates/xkb_includes.j2') }}" 
    insertafter: 'xkb_symbols \"basic\" \{'
    marker: "// {mark} ANSIBLE MANAGED BLOCK"
    regexp: both_capslock_cancel
  notify:
    - reload keyboard layout

- name: create ramdisk
  mount:
    path: /media/ramdisk
    src: ramdisk
    fstype: tmpfs
    opts: nodev,nosuid,noexec,nodiratime,size={{ ramdisk_size }}
    state: mounted
  become: yes

- name: install user-startup service
  template:
    src: user-startup.service.j2
    dest: /etc/systemd/system/user-startup.service
  become: yes
  register: user_startup_installation

- name: propagate service changes
  systemd: daemon_reload=yes
  become: yes
  changed_when: yes
  when: user_startup_installation.changed

- name: enable user-startup
  service:
    name: user-startup
    enabled: true
  become: yes

