#!/usr/bin/env bash
if [ -f /run/current-system/sw/share/nix-direnv/direnvrc ]; then
    source /run/current-system/sw/share/nix-direnv/direnvrc
else
    source "$(nix-env -q nix-direnv --out-path | cut -d' ' -f 3)/share/nix-direnv/direnvrc"
fi

: ${XDG_CACHE_HOME:=$HOME/.cache}
declare -A direnv_layout_dirs
direnv_layout_dir() {
    echo "${direnv_layout_dirs[$PWD]:=$(
        echo -n "$XDG_CACHE_HOME"/direnv/layouts/
        echo -n "$PWD" | shasum | cut -d ' ' -f 1
    )}"
}
