#!/usr/bin/env bash
if [ -f /run/current-system/sw/share/nix-direnv/direnvrc ]; then
    source /run/current-system/sw/share/nix-direnv/direnvrc
else
    # source "$(nix profile list | grep 'Store paths' | grep nix-direnv | awk '{print $3}')/share/nix-direnv/direnvrc"
    # source "$(nix-env -q nix-direnv --out-path | cut -d' ' -f 3)/share/nix-direnv/direnvrc"
    :
fi

: "${XDG_CACHE_HOME:="${HOME}/.cache"}"
declare -A direnv_layout_dirs
direnv_layout_dir() {
    local hash path
    echo "${direnv_layout_dirs[$PWD]:=$(
        hash="$(sha1sum - <<< "$PWD" | head -c40)"
        path="${PWD//[^a-zA-Z0-9]/-}"
        echo "${XDG_CACHE_HOME}/direnv/layouts/${hash}${path}"
    )}"
}
