#!/bin/sh
scenery=~/.wallpaper/wp.jpg
overlay=~/.wp-overlay.local
generated_wallpaper_path=/tmp/_wallpaper.jpg

if [ -f ~/.wp-overlay.local ]; then
    convert $scenery $overlay -gravity center -define compose:args=80 -compose blend \
        -composite $generated_wallpaper_path
else
    cp $scenery $generated_wallpaper_path
fi

# TODO: generalize over Xresources, resolution and border width
convert $generated_wallpaper_path -fill '#839496' -stroke '#839496' -strokewidth 3 -draw "rectangle 0,1056 1920,1059" $generated_wallpaper_path

feh --no-fehbg --bg-center --image-bg 'black' $generated_wallpaper_path
