---
- name: install dns utils
  package: name={{ item }} state=latest
  loop:
    - dnsmasq
    - resolvconf
  become: yes
  tags:
    - pkg
    - dns

- name: configure dnsmasq
  copy:
    src: dnsmasq/dnsmasq.conf
    dest: /etc/dnsmasq.conf
  become: yes
  tags:
    - dns

- name: configure resolvconf
  copy:
    src: resolvconf/
    dest: /etc/resolvconf/
  become: yes
  tags:
    - dns

- name: start dnsmasq
  service:
    name: dnsmasq
    enabled: true
    state: started
  become: yes
  tags:
    - dns

