---
- name: configure dotfiles
  file:
    src: ~/Dotfiles/dotfilesrc
    dest: ~/.dotfilesrc
    state: link

- name: gather dotfiles check information
  command: "{{ dotfiles_binary }} -c"
  changed_when: False
  register: dotfiles_check_result

- name: sync my Dotfiles
  command: "{{ dotfiles_binary }} --sync --force"
  when: dotfiles_check_result.stdout

- name: link main git identity
  file:
    state: link
    src: ~/Keys/git-main-id
    dest: "{{ ansible_user_dir }}/.gitid"
  when: link_main_git_id | bool
  ignore_errors: yes # TODO: make this emmit warning but don't stop the whole playbook
