---
- name: install dotfiles
  pip:
    name: dotfiles
    executable: pip3
    extra_args: --user
  tags:
    - pkg

- name: clone Dotfiles repository
  git:
    repo: "{{ dotfiles_repo_fetch_url }}"
    dest: ~/Dotfiles
    version: master
  ignore_errors: yes # added for local ansible files developement - local changes are present in the repository

- name: set remote-push over SSH for Dotfiles repo
  git_config:
    name: remote.origin.pushurl
    scope: local
    value: "{{ dotfiles_repo_push_url }}"
    repo: ~/Dotfiles
  tags:
    - hax

- name: configure dotfiles
  file:
    src: ~/Dotfiles/dotfilesrc
    dest: ~/.dotfilesrc
    state: link

- name: gather dotfiles check information
  command: "{{ dotfiles_binary }} -c"
  changed_when: False
  register: dotfiles_check_result

- name: sync my Dotfiles
  command: "{{ dotfiles_binary }} --sync --force"
  when: dotfiles_check_result.stdout

- name: link main git identity
  file:
    state: link
    src: ~/Keys/git-main-id
    dest: "{{ ansible_user_dir }}/.gitid"
  when: link_main_git_id | bool
  ignore_errors: yes # TODO: make this emmit warning but don't stop the whole playbook
