---
- name: install system packages
  package: name={{ item }} state=latest
  with_items:
    - git
    - python3
    - python3-pip

    - vim-gtk # vim with scripting languages and X11 integration
    - tmux # terminal multiplexer
    - htop # process diagnostics
    - ranger # file exploler
    - make # build / script automation
    - curl 
    - net-tools
    - unzip

    - network-manager

    - openvpn
    - ncftp # improved FTP client
  become: yes

- include_tasks: dotfiles.yml

- include_tasks: system/main.yml
- include_tasks: linuxbrew.yml
- include_tasks: vpn.yml

- include_tasks: vim.yml
