---
- name: install system packages
  package: name={{ item }} state=latest
  with_items:
    - git
    - python3
    - python3-pip

    - vim-gtk # vim with scripting languages and X11 integration
    - tmux # terminal multiplexer
    - htop # process diagnostics
    - ranger # file exploler
    - make # build / script automation
    - curl 
    - net-tools
    - unzip
    - expect # interactive script automation utility

    - network-manager

    - openvpn
    - ncftp # improved FTP client
    - wireshark # packet sniffing / analyzing
    - wakeonlan
  become: yes

- name: install python packages
  pip:
    name:
      - ptpython # improved Python shell
      - pygments-style-solarized # colorscheme
      - httpie # curl on drugs
      - pirate-get # command line for the pirate bay
    state: latest
    executable: pip3
    extra_args: --user

- include_tasks: dotfiles.yml

- include_tasks: system/main.yml
- include_tasks: vpn.yml

- include_tasks: vim.yml
