---
- name: ensure .vim directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - ~/.vim/colors
    - ~/.vim/bundle
    - ~/.vim/undo
    - ~/.vim/spell

- name: install Vundle
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: ~/.vim/bundle/Vundle.vim
    version: master

- name: install solarized colorscheme
  # since the last commit was in 2011 I've decided to vendor-in this one
  copy:
    dest: ~/.vim/colors/solarized.vim
    src: vim/solarized.vim
    mode: '600'

- name: gather installed plugins information
  command: ls ~/.vim/bundle -1
  changed_when: False
  register: vim_installed_plugins_result

- name: gather desired plugins information
  shell: cat ~/.vimrc | grep Plugin | grep -v -e ^\" | cut -d/ -f 2 | tr -d \'
  changed_when: False
  register: vim_desired_plugins_result

- set_fact:
    vim_installed_plugins: "{{ vim_installed_plugins_result.stdout_lines | sort }}"
    vim_desired_plugins: "{{ vim_desired_plugins_result.stdout_lines | sort }}"

- name: install plugins
  command: vim -i NONE +PluginInstall +qall
  when: vim_installed_plugins != vim_desired_plugins

- name: download non-English dictionaries
  get_url:
    url: "http://ftp.vim.org/pub/vim/runtime/spell/{{item}}.utf-8.spl"
    dest: "~/.vim/spell/{{item}}.utf-8.spl"
    mode: '600'
  with_items:
    - pl
