---

- name: install system packages
  package: name={{ item }} state=latest
  with_items:
    - screenkey # Displays pressed keys, cool for presentations
    - xcape # Ctrl => ESC | Ctrl
  become: yes

