---

- name: install system packages
  package: name={{ item }} state=latest
  with_items:
    - graphviz # graph visualization
  become: yes

- name: install python devtools
  pip:
    name:
      - ptpython # improved Python shell
      - BlastRadius # Terraform graphs exploration tool
    executable: pip3
    extra_args: --user

- name: symlink .vimrc and .ideavimrc (for Jetbrains' software)
  file:
    src: ~/.vimrc
    dest: ~/.ideavimrc
    state: link

# Install Pycharm, etc.
