---
- name: install Docker
  include_role:
    name: geerlingguy.docker
    apply:
      become:
        yes
  vars:
    docker_users:
      - "{{ ansible_env.USER }}"
    docker_package_state: latest

- name: install system packages
  package: name={{ item }} state=latest
  with_items:
    - graphviz # graph visualization

    - gdb # C / C++ debugger
    - shellcheck # sh linter

    - gcc
    - g++
    - python3-venv
    - python-virtualenv
  become: yes

- name: remove system packages
  package: name={{ item }} state=absent
  with_items:
    - nano
  become: yes

- name: install python devtools
  pip:
    name:
      - BlastRadius # Terraform graphs exploration tool
      - pytest
    executable: pip3
    state: latest
    extra_args: --user

- name: symlink .vimrc and .ideavimrc (for Jetbrains' software)
  file:
    src: ~/.vimrc
    dest: ~/.ideavimrc
    state: link

# Install Pycharm, etc.

- include_tasks: rust.yml
