---

- name: install system packages
  package: name={{ item }} state=latest
  with_items:
    - graphviz # graph visualization
    - gdb # C / C++ debugger
    - python3-venv
    - python-virtualenv
  become: yes

- name: install python devtools
  pip:
    name:
      - ptpython # improved Python shell
      - BlastRadius # Terraform graphs exploration tool
      - httpie # curl on drugs
    executable: pip3
    extra_args: --user

- name: symlink .vimrc and .ideavimrc (for Jetbrains' software)
  file:
    src: ~/.vimrc
    dest: ~/.ideavimrc
    state: link

# Install Pycharm, etc.
