- name: Stat rustup binary
  stat:
    path: ~/.cargo/bin/rustup
  register: rustup

- set_fact:
    rustup_is_installed: "{{ rustup.stat.exists }}"
    random_string: "{{ (999999999999999999999 | random | string + (lookup('pipe', 'date +%s%N'))) | to_uuid() }}"

- name: install Rust (+toolchain)
  block:
    - name: Download rustup installation script
      get_url:
        url: https://sh.rustup.rs 
        checksum: sha512:2e8eba09edf5e78bf2fadd9997affb228feb22c7b5f39f20f2edefba1b65e492fd1429056647cd8f2aaed204eb7662f9fd8d84852dc86aea00b285f5735ebd1d
        dest: "/tmp/{{ random_string }}"
        mode: u+x
      register: rustup_installation_script

    - name: Execute the installation script
      command: 
      args:
        argv:
          - "{{ rustup_installation_script.dest | quote }}"
          - "-y"
          - "--no-modify-path"
  when: not rustup_is_installed

- name: Attempt rust update
  command: ~/.cargo/bin/rustup update
  register: rustup_update_attempt
  changed_when: "'unchanged' not in rustup_update_attempt.stdout"
