---

- name: install system packages
  package: name={{ item }} state=latest
  with_items:
    - xorg
    - i3 # Window manager
    - i3blocks
    - fonts-font-awesome # Icons for i3bar
    - xcape # Ctrl => ESC | Ctrl
    - terminator # Terminal emulator
    - pulseaudio # I know it's technically not related to x ;)

    - imagemagick # contains `convert` package, a dependency of my fancy lock script
    - screenkey # Displays pressed keys, cool for presentations
    - feh # Vim-like picture viewer
    - arandr # GUI for xrandr
    - scrot # Screenshot utility
    - pavucontrol # Volume control - TODO: Consider dropping in favour of alsamixer
    - alsa-utils # Volume control

    - weechat # IRC
    - vlc # media player
    - evince # PDF reader
    - workrave # forces me to take breaks

  become: yes

- name: install sensible browser
  block:
    - name: install firefox
      block:
        - name: install latest firefox
          package: name=firefox state=latest
      rescue:
        - name: install some firefox
          package: name=firefox state=present

    - name: remove firefox-esr
      package: name=firefox-esr state=absent
  rescue:
    - name: install firefox-esr
      package: name=firefox-esr state=present
  always:
    - name: remove iceweasel
      package: name=iceweasel  state=absent
  become: yes

- name: install contrib i3blocks scripts
  git:
    repo: https://github.com/vivien/i3blocks-contrib
    dest: /opt/i3blocks
    depth: 1
    version: master
  become: yes

- name: install Source Code Pro font
  git:
    repo: https://github.com/adobe-fonts/source-code-pro.git
    dest: ~/.local/share/fonts/source-code-pro
    depth: 1
    version: release
    force: true
  notify:
    - reload font cache for Source Code Pro
  # TODO: https://github.com/adobe-fonts/source-code-pro/issues/17#issuecomment-332018295 <- do this in a better way
