---

- name: install system packages
  package: name={{ item }} state=latest
  with_items:
    - xorg
    - i3 # Window manager
    - i3blocks
    - fonts-font-awesome # Icons for i3bar
    - xcape # Ctrl => ESC | Ctrl
    - terminator # Terminal emulator

    - screenkey # Displays pressed keys, cool for presentations
    - feh # Vim-like picture viewer
    - arandr # GUI for xrandr
    - scrot # Screenshot utility

    - weechat # IRC

  become: yes

# TODO: Plan on which browser package is avaible and then simply execute the plan

- name: install sensible browser
  block:
    - name: install firefox
      package: name=firefox-esr state=latest

    - name: remove iceweasel
      package: name=iceweasel state=absent
  rescue:
    - name: ensure iceweasel is installed
      package: name=iceweasel state=present
  become: yes

- name: install contrib i3blocks scripts
  git:
    repo: https://github.com/vivien/i3blocks-contrib
    dest: /opt/i3blocks
    depth: 1
    version: master
  become: yes

- name: install Source Code Pro font
  git:
    repo: https://github.com/adobe-fonts/source-code-pro.git
    dest: ~/.local/share/fonts/source-code-pro
    depth: 1
    version: release
    force: true
  notify:
    - reload font cache for Source Code Pro
  # TODO: https://github.com/adobe-fonts/source-code-pro/issues/17#issuecomment-332018295 <- do this in a better way
