---
- name: Install git - in order to clone Dotfiles repository
  package: name=git state=latest
  become: yes

- name: Install python3 and pip3 - as a dependency of dotfiles
  package: name={{ item }} state=latest
  with_items:
    - python3
    - python3-pip
  become: yes

- name: Install dotfiles
  pip: name=dotfiles executable=pip3

- name: Clone Dotfiles repository
  git:
    repo: https://github.com/allgreed/dotfiles.git
    dest: ~/Dotfiles
    version: master
  ignore_errors: yes # added for local ansible files developement - local changes are present in the repository

- name: Configure dotfiles
  file:
    src: ~/Dotfiles/dotfilesrc
    dest: ~/.dotfilesrc
    state: link

- name: Sync my Dotfiles
  shell: |
    TMP_ANSIBLE_DOTFILES_STATUS_CHECK="$(dotfiles -c)"
    test -z "$TMP_ANSIBLE_DOTFILES_STATUS_CHECK" || dotfiles --sync --force
    echo $TMP_ANSIBLE_DOTFILES_STATUS_CHECK
  register: command_result
  changed_when: command_result.stdout

