---
- name: Install git - in order to clone Dotfiles repository
  package: name=git state=latest
  become: yes

- name: Install python3 and pip3 - as a dependency of dotfiles
  package: name={{ item }} state=latest
  with_items:
    - python3
    - python3-pip
  become: yes

- name: Install dotfiles
  pip:
    name: dotfiles
    executable: pip3
    extra_args: --user

- name: Clone Dotfiles repository
  git:
    repo: https://github.com/allgreed/dotfiles.git
    dest: ~/Dotfiles
    version: master
  ignore_errors: yes # added for local ansible files developement - local changes are present in the repository

- name: Set remote-push over ssh for Dotfiles repo
  git_config:
    name: remote.origin.pushurl
    scope: local
    value: git@github.com:allgreed/dotfiles.git
    repo: ~/Dotfiles

- name: Configure dotfiles
  file:
    src: ~/Dotfiles/dotfilesrc
    dest: ~/.dotfilesrc
    state: link

- name: Sync my Dotfiles
  shell: |
    DOTFILES="~/.local/bin/dotfiles"
    TMP_ANSIBLE_DOTFILES_STATUS_CHECK="$(eval $DOTFILES -c)"
    test -z "$TMP_ANSIBLE_DOTFILES_STATUS_CHECK" || eval $DOTFILES --sync --force
    echo $TMP_ANSIBLE_DOTFILES_STATUS_CHECK
  register: command_result
  changed_when: command_result.stdout

