---

- name: install Vim with scripting languages support
  package: name=vim-nox state=latest
  become: yes

- name: ensure .vim directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - ~/.vim/colors
    - ~/.vim/bundle

- name: install Vundle
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: ~/.vim/bundle/Vundle.vim
    version: master

- name: install solarized colorscheme
  # since the last commit was in 2011 I've decided to vendor-in this one
  copy:
    dest: ~/.vim/colors/solarized.vim
    src: solarized.vim

- name: gather installed plugins information
  command: ls ~/.vim/bundle -1
  changed_when: False
  register: vim_installed_plugins_result

- set_fact:
    vim_installed_plugins: "{{ vim_installed_plugins_result.stdout_lines }}"
    #vim_installed_plugins_count: "{{ vim_installed_plugins | length }}"

- name: install plugins
  command: vim -i NONE +PluginInstall +qall
  when: vim_installed_plugins == ["Vundle.vim"]
