---

- name: install Vim with scripting languages support
  package: name=vim-nox state=latest
  become: yes

- name: install Vundle
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: ~/.vim/bundle/Vundle.vim
    version: master

- name: ensure "~/.vim/colors" directory
  file:
    path: ~/.vim/colors
    state: directory
    recurse: yes

- name: install solarized colorscheme
  # since the last commit was in 2011 I've decided to vendor-in this one
  copy:
    dest: ~/.vim/colors/solarized.vim
    src: solarized.vim

- name: install Vundle plugins
  shell: |
    INSTALLED_PLUGIN_COUNT="$(ls ~/.vim/bundle | wc -l)"
    if [ $INSTALLED_PLUGIN_COUNT == "1" ]
        then
            vim -i NONE +PluginInstall +qall
    fi
  args:
    executable: /bin/bash
  register: command_result
  changed_when: command_result.stdout
