#!/usr/bin/env python3
import sys
import re

def main():
    if sys.argv[1] == "smudge":
        smudge()
    elif sys.argv[1] == "clean":
        clean()
    else:
        raise RuntimeError("wrong mode, choose either smudge or clean")


def clean():
    for line in sys.stdin:
        line = re.sub(r"main_window\.(x|y)=(-?\d+)",r"main_window.\1=255", line)
        line = re.sub(r"operation-mode=\d",r"operation-mode=0", line)
        # line = re.sub(r"operation-mode=\d",r"operation-mode=0", line)

        print(line, end="")


def smudge():
    for line in sys.stdin:
        print(line, end="")
	

if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print(e)
        print("err")
