#!/usr/bin/env bash
set -o xtrace

lock_img_path="/tmp/lock-img.png"
screen_path="/tmp/screen-dump.jpg"

# pre-fastlock
scrot -o $screen_path
convert $screen_path -filter point -resize 10% -resize 1000% $lock_img_path

# fastlock
which i3lock-color && {
    i3lock-color -n -i $lock_img_path --ignore-empty-password --pass-volume-keys &
} || {
    i3lock -n -i $lock_img_path &
}
fastlock_pid=$!

# pre-lock
dunstctl set-paused true & wait_pids+=($!)
physlock -lds & wait_pids+=($!)
ssh-add -D & wait_pids+=($!)
convert $screen_path -filter point -resize 10% -resize 1000% -paint 3 $lock_img_path & wait_pids+=($!)

# actual lock
wait "${wait_pids[@]}" # ensure all pre-lock stuff is done
kill $fastlock_pid
# TODO: can I do something about the flash?
which i3lock-color && {
    i3lock-color -n -i $lock_img_path --ignore-empty-password --pass-volume-keys
} || {
    i3lock -n -i $lock_img_path
}

# unlock
physlock -Lds
dunstctl set-paused false
