#!/usr/bin/env bash
set -o xtrace

screen_path="/tmp/screen-dump.jpg"

# pre-lock
physlock -lds & wait_pids+=($!)
ssh-add -D & wait_pids+=($!)

# prepare
scrot $screen_path
convert $screen_path -filter point -resize 10% -resize 1000% -paint 3 $screen_path

wait "${wait_pids[@]}"

# actual lock
i3lock-color -n -i $screen_path --ignore-empty-password --pass-volume-keys

# unlock
physlock -Lds
