#!/usr/bin/env bash
set -o xtrace

lock_img_path="/tmp/lock-img.jpg"
screen_path="/tmp/screen-dump.jpg"

# pre-fastlock
scrot -o $screen_path
convert $screen_path -filter point -resize 10% -resize 1000% $lock_img_path

# fastlock
i3lock-color -n -i $lock_img_path --ignore-empty-password --pass-volume-keys &
fastlock_pid=$!

# pre-lock
physlock -lds & wait_pids+=($!)
ssh-add -D & wait_pids+=($!)
convert $screen_path -filter point -resize 10% -resize 1000% -paint 3 $lock_img_path & wait_pids+=($!)

# actual lock
wait "${wait_pids[@]}" # ensure all pre-lock stuff is done
kill $fastlock_pid
# TODO: can I do something about the flash?
i3lock-color -n -i $lock_img_path --ignore-empty-password --pass-volume-keys

# unlock
physlock -Lds
