#!/bin/sh
# vim: ft=sh
INOTIFYWAIT_SYMLINK_TARGET="$HOME/Desktop/inotifywait-symlink-target/target/release/inotifywait-symlink-target"
NIX_MANIFEST_FORMAT="$HOME/Desktop/nix-manifest-format/target/release/nix-manifest-format"

. ~/.nix-profile/etc/profile.d/nix.sh  # apply nix environment

if [ ! -f "$INOTIFYWAIT_SYMLINK_TARGET" ]; then 
    cargo build --release --manifest-path ~/Desktop/inotifywait-symlink-target/Cargo.toml
fi

if [ ! -f "$NIX_MANIFEST_FORMAT" ]; then
    cargo build --release --manifest-path ~/Desktop/nix-manifest-format/Cargo.toml
fi

$INOTIFYWAIT_SYMLINK_TARGET
$NIX_MANIFEST_FORMAT > ~/Dotfiles/nix/manifest.nix
