---
- hosts: all
  roles:
    - role: dotfiles
      dotfiles_repo: https://github.com/allgreed/dotfiles.git
      dotfiles_repo_push_url: git@github.com:allgreed/dotfiles.git

    - role: docker

    - role: vim
    - role: cli_utilities

    - role: x_utilities

    - role: keyboard
    - role: chat
    - role: x_dev
